export const artifactDict: { [key: string]: { id: string, name: string } } = {
  "Code-Scan (Bandit Code Scan Bandit)": { id: "bandit", name: "bandit.log" },
  "Code-Scan (DocStyle Code Scan DocStyle)": { id: "pydocstyle", name: "pydocstyle.log" },
  "Code-Scan (Pylint Code Scan Pylint)": { id: "pylint", name: "pylint.json" },
  "Code-Scan-Neural-Insights (Bandit Code Scan Bandit)": { id: "bandit", name: "bandit.log" },
  "Code-Scan-Neural-Insights (DocStyle Code Scan DocStyle)": { id: "pydocstyle", name: "pydocstyle.log" },
  "Code-Scan-Neural-Insights (Pylint Code Scan Pylint)": { id: "pylint", name: "pylint.json" },
  "Code-Scan-Neural-Solution (Bandit Code Scan Bandit)": { id: "bandit", name: "bandit.log" },
  "Code-Scan-Neural-Solution (DocStyle Code Scan DocStyle)": { id: "pydocstyle", name: "pydocstyle.log" },
  "Code-Scan-Neural-Solution (Pylint Code Scan Pylint)": { id: "bandit", name: "bandit.log" },
  "Model-Test (Generate Report GenerateReport)": { id: "FinalReport", name: "report.html" },
  "UT-Basic (Coverage Combine CollectDatafiles)": { id: "UT_coverage_report", name: "coverage_compare.html" },
  "UT-Basic (Unit Test FWKs adaptor Test FWKs adaptor)": { id: "ut_adaptor_report", name: "ut_tf_2.14.0_pt_2.1.0+cpu.log" },
  "UT-Basic (Unit Test FWKs adaptor baseline Test FWKs adaptor baseline)": { id: "ut-base_adaptor_report", name: "ut_tf_2.14.0_pt_2.1.0+cpu.log" },
  "UT-Basic (Unit Test ITEX Test ITEX)": { id: "ut_itex_report", name: "ut_itex.log" },
  "UT-Basic (Unit Test ITEX baseline Test ITEX baseline)": { id: "'ut-base_itex_report", name: "ut_itex.log" },
  "UT-Basic (Unit Test Pruning Test PyTorch Pruning)": { id: "ut_pt-pruning_report", name: "ut_pt_pruning.log" },
  "UT-Basic (Unit Test Pruning Test TensorFlow Pruning)": { id: "ut_tf-pruning_report", name: "ut_tf_pruning.log" },
  "UT-Basic (Unit Test Pruning baseline Test PyTorch Pruning baseline)": { id: "ut-base_pt-pruning_report", name: "ut_pt_pruning.log" },
  "UT-Basic (Unit Test Pruning baseline Test TensorFlow Pruning baseline)": { id: "ut-base_tf-pruning_report", name: "ut_tf_pruning.log" },
  "UT-Basic (Unit Test TF newAPI Test TF newAPI)": { id: "ut_tfnewapi_report", name: "ut_tf_newapi.log" },
  "UT-Basic (Unit Test TF newAPI baseline Test TF newAPI baseline)": { id: "ut-base_tfnewapi_report", name: "ut_tf_newapi.log" },
  "UT-Basic (Unit Test User facing API Test User facing API)": { id: "ut_api_report", name: "ut_tf_2.14.0_pt_2.1.0+cpu.log" },
  "UT-Basic (Unit Test User facing API baseline Test User facing API baseline)": { id: "ut-base_api_report", name: "ut_tf_2.14.0_pt_2.1.0+cpu.log" },
  "UT-Basic (Unit Test other basic case Test other basic case)": { id: "ut_others_report", name: "ut_tf_2.14.0_pt_2.1.0+cpu.log" },
  "UT-Basic (Unit Test other cases baseline Test other cases baseline)": { id: "ut-base_others_report", name: "ut_tf_2.14.0_pt_2.1.0+cpu.log" },
  "UT-Basic-No-Coverage (Unit Test FWKs adaptor Test FWKs adaptor)": { id: "ut-adaptor", name: "ut_tf_2.13.0_pt_2.0.1+cpu.log" },
  "UT-Basic-No-Coverage (Unit Test Pruning Test PyTorch Pruning)": { id: "ut-coverage-pt-pruning", name: "ut_pt_pruning.log" },
  "UT-Basic-No-Coverage (Unit Test Pruning Test TensorFlow Pruning)": { id: "ut-coverage-tf-pruning", name: "ut_tf_pruning.log" },
  "UT-Basic-No-Coverage (Unit Test User facing API Test User facing API)": { id: "ut-coverage-api", name: "ut_tf_2.13.0_pt_2.0.1+cpu.log" },
  "UT-Basic-No-Coverage (Unit Test other basic case Test other basic case)": { id: "ut-others", name: "ut_tf_2.13.0_pt_2.0.1+cpu.log" },
  "UT-ITREX": { id: "ut-itrex", name: "ut_itrex.log" },
  "UT-Neural-Insights": { id: "ut-neural-insight", name: "ut_neural_insight.log" },
  "UT-Neural-Solution": { id: "ut-neural-solution", name: "ut_neural_solution.log" },
  "UT-Coder": { id: "ut-ncoder", name: "ut_neural_coder.log" },
  "UT-3x-TensorFlow (Coverage Combine CollectDatafiles)": { id: "UT_coverage_report_3x_tf", name: "zip" },
  "UT-3x-TensorFlow (Unit Test 3x TensorFlow Unit Test 3x TensorFlow)": { id: "ut_3x_report", name: "report.html" },
  "UT-3x-TensorFlow (Unit Test 3x TensorFlow baseline Unit Test 3x TensorFlow baseline)": { id: "ut_3x_baseline_report", name: "report.html" },
  "UT-3x-Torch (Coverage Combine CollectDatafiles)": { id: "UT_coverage_report_3x_pt", name: "zip" },
  "UT-3x-Torch (Unit Test 3x Torch Unit Test 3x Torch)": { id: "ut_3x_report", name: "report.html" },
  "UT-3x-Torch (Unit Test 3x Torch baseline Unit Test 3x Torch baseline)": { id: "ut_3x_baseline_report", name: "report.html" },
  "UT-3x-ONNXRT (Coverage Combine CollectDatafiles)": { id: "UT_coverage_report_3x_ort", name: "zip" },
  "UT-3x-ONNXRT (Unit Test 3x ONNXRT Unit Test 3x ONNXRT)": { id: "ut_3x_report", name: "report.html" },
  "UT-3x-ONNXRT (Unit Test 3x ONNXRT baseline Unit Test 3x ONNXRT baseline)": { id: "ut_3x_baseline_report", name: "report.html" },
}
