export const artifactDict: { [key: string]: { id: string, name: string } } = {
  "format-scan (pylint)": { id: "pylint", name: "zip" },
  "format-scan (bandit)": { id: "bandit", name: "zip" },
  "format-scan (clangformat)": { id: "clangformat", name: "zip" },
  "format-scan (cloc)": { id: "cloc", name: "zip" },
  "format-scan (cpplint)": { id: "cpplint", name: "zip" },
  "optimize-unit-test-baseline": { id: "UnitTestbaseline", name: "zip" },
  "optimize-unit-test-PR-test": { id: "UnitTestPR-test", name: "zip" },
  "Genreate-OptimizeUT-Report": { id: "Optimize Unit Test", name: "zip" },
  "neural-speed-unit-test": { id: "LLM Runtime Unit Test", name: "zip" },
  "neuralchat-unit-test-baseline": { id: "UnitTestbaseline", name: "zip" },
  "neuralchat-unit-test-PR-test": { id: "UnitTestPR-test", name: "zip" },
  "Generate-NeuralChat-Report": { id: "Neural Chat Unit Test", name: "zip" },
  "engine-unit-test-baseline": { id: "UnitTestbaseline", name: "zip" },
  "engine-unit-test-PR-test": { id: "UnitTestPR-test", name: "zip" },
  "Genreate-Engine-Report": { id: "Engine Unit Test", name: "zip" },
  "sparselib": { id: "SparseLib Test", name: "zip" },
}
